version: "3.8"

services:
  voidr.id.server:
    image: ${DOCKER_REGISTRY-}voidr.id.server
    build:
      context: .
      dockerfile: src/Server/Dockerfile
    depends_on:
      - postgres
    secrets:
      - postgres_password

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - postgres_password

secrets:
  postgres_password:
    file: postgres_password.txt

volumes:
  postgres_data:
